
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: myuser
#   password: mypassword
#   host: localhost
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: nvamOLzSCQCkuAcooTmGjDwpiOBVgPTQ
  host: yamabiko.proxy.rlwy.net
  port: 15721
  database: railway
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: pos_api_development

test:
  <<: *default
  database: pos_api_test
production:
  <<: *default
  database: pos_api_production
  username: pos_api
  password: <%= ENV["POS_API_DATABASE_PASSWORD"] %>
